stages:
  prepare_training:
    cmd: uv run python src/glm/preprocess_2detect.py mode2 train
    deps:
    - src/glm/preprocess_2detect.py
    - ${data.raw_path}
    params:
    - data
    outs:
    - ${data.processed_path}:
        cache: false

  pretraining:
    cmd: uv run torchrun --nproc_per_node=2 src/glm/pretrain.py
    deps:
    - src/glm/pretrain.py
    - ${data.processed_path}
    params:
    - pretrain_parameters
    outs:
    - dvclive
    - src/glm/saved_models/pretrained_sinogram_model.pt

  training:
    cmd: uv run torchrun --nproc_per_node=2 src/glm/train.py
    params:
    - pretrain_parameters
    - train_parameters
    deps:
    - src/glm/train.py
    - ${data.processed_path}
    - src/glm/saved_models/pretrained_sinogram_model.pt
    outs:
    - src/glm/saved_models/end_to_end_model.pt

params:
- params.yaml
- dvclive/params.yaml
artifacts:
  pretrained_sinogram_model:
    path: src/glm/saved_models/pretrained_sinogram_model.pt
    type: model
    desc: Pretrained model for sinogram processing

  end_to_end_model:
    path: src/glm/saved_models/end_to_end_model.pt
    type: model

metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
